### ISSUE TITLE
Doesn't work with jQuery 1.7.0

### ISSUE THREAD

**Issue by Hp93** [crlcu/multiselect#62]
The following error is thrown when using with [jQuery 1.7.0](https://code.jquery.com/jquery-1.7.0.min.js):

> TypeError: $.expr.createPseudo is not a function

A google search lead me to [this SO](http://stackoverflow.com/questions/12404653/jquery-case-insensitive-contains-selector-1-8-1), which does solve the issue, but I'm not sure if it would effect some functions.

**Comment by crlcu** [comment]
Hi @Hp93 

Thanks for pointing out this issue.
The fix is now on master.
